@BookStore.API_HostAddress = http://localhost:5101

GET {{BookStore.API_HostAddress}}/books/

###
GET {{BookStore.API_HostAddress}}/books/da07ce22-6051-487b-12a2-08dd17ec49d8

###
POST {{BookStore.API_HostAddress}}/books
Content-Type: application/json

{
    "title": "To Kill a Mockingbird",
    "author": "Harper Lee",
    "isbn": "9780061120084",
    "publishedDate": "1960-07-11",
    "genreId": "5888EE0E-6235-48B0-366E-08DD17DF2016",
    "pageCount": 281,
    "description": "A novel about the serious issues of race and rape in 1930s Alabama.",
    "publisher": "J.B. Lippincott & Co."
}

###
DELETE {{BookStore.API_HostAddress}}/books/78f65244-8325-4aac-acf4-c95575655920

###
GET {{BookStore.API_HostAddress}}/genres/
