@BookStore.API_HostAddress = http://localhost:5101

GET {{BookStore.API_HostAddress}}/books/

###
GET {{BookStore.API_HostAddress}}/books/da07ce22-6051-487b-12a2-08dd17ec49d8

###
POST {{BookStore.API_HostAddress}}/books
Content-Type: application/json

{
    "title": "Harry Potter and the Sorcerer’s Stone",
    "authorId": "57F8CD53-6840-4913-ADC9-08DD2ABA76D8",
    "isbn": "9780439708180",
    "publishedDate": "1997-06-26",
    "genreId": "F0E31FD0-7F3C-4A1B-1DB2-08DD2ABA76CC",
    "pageCount": 309,
    "description": "A young wizard discovers his magical heritage and attends Hogwarts School of Witchcraft and Wizardry.",
    "publisher": "Scholastic"
}

###
DELETE {{BookStore.API_HostAddress}}/books/78f65244-8325-4aac-acf4-c95575655920

###
GET {{BookStore.API_HostAddress}}/genres/

###
POST {{BookStore.API_HostAddress}}/authors
Content-Type: application/json

{
    "name": "Diego Ramirez"
}
